//Lorcana Card JSON Database

var lorcanadb = {
    "firstChapterAmber": [
        {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_001-204_Ariel-OnHumanLegs.webp",
            "number": "001",
            "setId": "001/204\u2022EN\u20221",
            "name": "ARIEL",
            "subname": "On Human Legs",
            "ink": "Amber",
            "classification": "Storyborn Hero Princess",
            "rarity": "Uncommon",
            "cost": "4",
            "strength": "3",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Matthew Robert Davies",
            "description": "VOICELESS: This character can't '' to sing songs."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_002-204_Ariel-SpectacularSinger.webp",
            "number": "002",
            "setId": "002/204\u2022EN\u20221",
            "name": "ARIEL",
            "subname": "Spectacular Singer",
            "ink": "Amber",
            "classification": "Storyborn Hero Princess",
            "rarity": "Super Rare",
            "cost": "3",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Alice Pisoni",
            "description": "MUSICAL DEBUT: When you play this character, look at the top 4 cards of your deck. You may reveal a song card and put it into your hand. Put the rest on the bottom of your deck in any order."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_003-204_Cinderella-GentleAndKind.webp",
            "number": "003",
            "setId": "003/204\u2022EN\u20221",
            "name": "CINDERELLA",
            "subname": "Gentle and Kind",
            "ink": "Amber",
            "classification": "Storyborn Hero Princess",
            "rarity": "Uncommon",
            "cost": "4",
            "strength": "2",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Javier Salas",
            "description": "A WONDERFUL DREAM: Remove up to 3 damage from chosen Princess character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_004-204_Goofy-Musketeer.webp",
            "number": "004",
            "setId": "004/204\u2022EN\u20221",
            "name": "GOOFY",
            "subname": "Musketeer",
            "ink": "Amber",
            "classification": "Dreamborn, Hero, Musketeer",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "3",
            "willpower": "6",
            "loreValue": "1",
            "artist": "Jochem Van Gool",
            "description": "AND TWO FOR TEA!: When you play this character, you may remove up to 2 damage from each of your Musketeer characters."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_005-204_Hades-KingOfOlympus.webp",
            "number": "005",
            "setId": "005/204\u2022EN\u20221",
            "name": "HADES",
            "subname": "King of Olympus",
            "ink": "Amber",
            "classification": "Floodborn Villain King Deity",
            "rarity": "Rare",
            "cost": "8",
            "strength": "6",
            "willpower": "7",
            "loreValue": "1",
            "artist": "Alex Accorsi",
            "description": "SINISTER PLOT: This character gets +1 lore for each other Villain character you have in play."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_006-204_Hades-LordOfTheUnderworld.webp",
            "number": "006",
            "setId": "006/204\u2022EN\u20221",
            "name": "HADES",
            "subname": "Lord of the Underworld",
            "ink": "Amber",
            "classification": "Storyborn Villain Deity",
            "rarity": "Rare",
            "cost": "4",
            "strength": "3",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Randy Bishop",
            "description": "WELL OF SOULS: When you play this character, return a character card from your discard to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_007-204_HeiHei-BoatSnack.webp",
            "number": "007",
            "setId": "007/204\u2022EN\u20221",
            "name": "HEIHEI",
            "subname": "Boat Snack",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "1",
            "strength": "1",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Jenna Gray",
            "description": "Support: Whenever this character quests, you may add their strength to another chosen character's strength this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_008-204_Lefou-Bumbler.webp",
            "number": "008",
            "setId": "008/204\u2022EN\u20221",
            "name": "LEFOU",
            "subname": "Bumbler",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "1",
            "willpower": "2",
            "loreValue": "2",
            "artist": "Andrey Chumak",
            "description": "LOYAL: If you have a character named Gaston in play, you pay 1 cost less to play this character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_009-204_Lilo-MakingAWish.webp",
            "number": "009",
            "setId": "009/204\u2022EN\u20221",
            "name": "LILO",
            "subname": "Making a Wish",
            "ink": "Amber",
            "classification": "Storyborn Hero",
            "rarity": "Rare",
            "cost": "1",
            "strength": "1",
            "willpower": "1",
            "loreValue": "2",
            "artist": "Dave Beauchene",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_010-204_Maximus-PalaceHorse.webp",
            "number": "010",
            "setId": "010/204\u2022EN\u20221",
            "name": "MAXIMUS",
            "subname": "Palace Horse",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Super Rare",
            "cost": "5",
            "strength": "4",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Brian Welsz",
            "description": "Bodyguard: This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able. Support: Whenever this character quests, you may add their strength to another chosen character's strength this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_011-204_Maximus-RelentlessPursuer.webp",
            "number": "011",
            "setId": "011/204\u2022EN\u20221",
            "name": "MAXIMUS",
            "subname": "Relentless Pursuer",
            "ink": "Amber",
            "classification": "Dreamborn Ally",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "3",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Kendall Hale",
            "description": "HORSE KICK: When you play this character, chosen character gets -2 strength this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_012-204_MickeyMouse-TrueFriend.webp",
            "number": "012",
            "setId": "012/204\u2022EN\u20221",
            "name": "MICKEY MOUSE",
            "subname": "True Friend",
            "ink": "Amber",
            "classification": "Storyborn Hero",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "3",
            "willpower": "3",
            "loreValue": "2",
            "artist": "Dave Beauchene",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_013-204_MinnieMouse-BelovedPrincess.webp",
            "number": "013",
            "setId": "013/204\u2022EN\u20221",
            "name": "MINNIE MOUSE",
            "subname": "Beloved Princess",
            "ink": "Amber",
            "classification": "Dreamborn Princess",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Kendall Hale",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_014-204_Moana-OfMotunui.webp",
            "number": "014",
            "setId": "014/204\u2022EN\u20221",
            "name": "MOANA",
            "subname": "Of Motunui",
            "ink": "Amber",
            "classification": "Storyborn Hero Princess",
            "rarity": "Rare",
            "cost": "5",
            "strength": "1",
            "willpower": "6",
            "loreValue": "3",
            "artist": "Nicolas Kole",
            "description": "WE CAN FIX IT: Whenever this character quests, you may ready your other Princess characters. They can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_015-204_Mr.Smee-LoyalFirstMate.webp",
            "number": "015",
            "setId": "015/204\u2022EN\u20221",
            "name": "MR. SMEE",
            "subname": "Loyal First Mate",
            "ink": "Amber",
            "classification": "Dreamborn Ally Pirate",
            "rarity": "Common",
            "cost": "3",
            "strength": "2",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Kamil Murzyn / Eri Welli",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_016-204_PrincePhillip-Dragonslayer.webp",
            "number": "016",
            "setId": "016/204\u2022EN\u20221",
            "name": "PRINCE PHILLIP",
            "subname": "Dragonslayer",
            "ink": "Amber",
            "classification": "Storyborn Hero Prince",
            "rarity": "Uncommon",
            "cost": "4",
            "strength": "3",
            "willpower": "3",
            "loreValue": "2",
            "artist": "Philipp Kruse",
            "description": "HEROISM: When this character challenges and is banished, you may banish the challenged character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_017-204_Pumbaa-FriendlyWarthog.webp",
            "number": "017",
            "setId": "017/204\u2022EN\u20221",
            "name": "PUMBAA",
            "subname": "Friendly Warthog",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "4",
            "strength": "3",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Jenna Gray",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_018-204_Rapunzel-GiftedWithHealing.webp",
            "number": "018",
            "setId": "018/204\u2022EN\u20221",
            "name": "RAPUNZEL",
            "subname": "Gifted With Healing",
            "ink": "Amber",
            "classification": "Storyborn Hero Princess",
            "rarity": "Legendary",
            "cost": "4",
            "strength": "1",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Jochem Van Gool",
            "description": "GLEAM AND GLOW: When you play this character, remove up to 3 damage from one of your characters. Draw a card for each 1 damage removed this way."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_019-204_Sebastian-CourtComposer.webp",
            "number": "019",
            "setId": "019/204\u2022EN\u20221",
            "name": "SEBASTIAN",
            "subname": "Court Composer",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Isaiah Mesq",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_020-204_Simba-ProtectiveCub.webp",
            "number": "020",
            "setId": "020/204\u2022EN\u20221",
            "name": "SIMBA",
            "subname": "Protective Cub",
            "ink": "Amber",
            "classification": "Storyborn Hero Prince",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Filipe Laurentino",
            "description": "Bodyguard: This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_021-204_Stitch-CarefreeSurfer.webp",
            "number": "021",
            "setId": "021/204\u2022EN\u20221",
            "name": "STITCH",
            "subname": "Carefree Surfer",
            "ink": "Amber",
            "classification": "Dreamborn, Hero, Alien",
            "rarity": "Legendary",
            "cost": "7",
            "strength": "4",
            "willpower": "8",
            "loreValue": "2",
            "artist": "Marcel Berg",
            "description": "OHANA: When you play this character, if you have 2 or more other characters in play, you may draw 2 cards."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_022-204_Stitch-NewDog.webp",
            "number": "022",
            "setId": "022/204\u2022EN\u20221",
            "name": "STITCH",
            "subname": "New Dog",
            "ink": "Amber",
            "classification": "Storyborn Hero Alien",
            "rarity": "Common",
            "cost": "1",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Alex Accorsi",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_023-204_Stitch-RockStar.webp",
            "number": "023",
            "setId": "023/204\u2022EN\u20221",
            "name": "STITCH",
            "subname": "Rockstar",
            "ink": "Amber",
            "classification": "Floodborn Hero Alien",
            "rarity": "Super Rare",
            "cost": "6",
            "strength": "3",
            "willpower": "5",
            "loreValue": "3",
            "artist": "Simangaliso Sibaya",
            "description": "ADORING FANS: Whenever you play this character with cost 2 or less, you may exert them to draw a card."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_024-204_Timon-GrubRustler.webp",
            "number": "024",
            "setId": "024/204\u2022EN\u20221",
            "name": "TIMON",
            "subname": "Grub Rustler",
            "ink": "Amber",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "1",
            "strength": "1",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Juan Diego Leon",
            "description": "TASTES LIKE CHICKEN: When you play this character, you may remove up to 1 damage from chosen character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_025-204_BeOurGuest.webp",
            "number": "025",
            "setId": "025/204\u2022EN\u20221",
            "name": "BE OUR GUEST",
            "subname": "",
            "ink": "Amber",
            "classification": "Action Song",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "R. La Barbara / L. Giammichele",
            "description": "Look at the top four cards of your deck. You may reveal a character card and put it into your hand. Put the rest on the bottom of your deck in any order."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_026-204_ControlYourTemper.webp",
            "number": "026",
            "setId": "026/204\u2022EN\u20221",
            "name": "CONTROL YOOUR TEMPER",
            "subname": "",
            "ink": "Amber",
            "classification": "Action",
            "rarity": "common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Amber Kommavongsa",
            "description": "Chosen character gets -2 strength this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_027-204_HAKUNAMATATA.webp",
            "number": "027",
            "setId": "027/204\u2022EN\u20221",
            "name": "HAKUNA MATATA",
            "subname": "",
            "ink": "Amber",
            "classification": "Action Song",
            "rarity": "Common",
            "cost": "4",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Juan Diego Leon",
            "description": "Remove up to 3 damage from each of your characters."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_028-204_HealingGlow.webp",
            "number": "028",
            "setId": "028/204\u2022EN\u20221",
            "name": "HEALING GLOW",
            "subname": "",
            "ink": "Amber",
            "classification": "Action",
            "rarity": "Common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Philipp Kruse",
            "description": "Remove up to 2 damage from chosen character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_029-204_JustInTime.webp",
            "number": "029",
            "setId": "029/204\u2022EN\u20221",
            "name": "JUST IN TIME",
            "subname": "",
            "ink": "Amber",
            "classification": "Action",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Leonardo Giammichele",
            "description": "You may play a character with cost 5 or less for free."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_030-204_PartOfYourWorld.webp",
            "number": "030",
            "setId": "030/204\u2022EN\u20221",
            "name": "PART OF YOUR WORLD",
            "subname": "",
            "ink": "Amber",
            "classification": "Action Song",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Samanta Erdini",
            "description": "Return a character card from your discard to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_031-204_YouHaveForgottenMe.webp",
            "number": "031",
            "setId": "031/204\u2022EN\u20221",
            "name": "YOU HAVE FORGOTTEN ME",
            "subname": "",
            "ink": "Amber",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "4",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Alice Pisoni",
            "description": "Each opponent chooses and discards 2 cards."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_032-204_Dinglehopper.webp",
            "number": "032",
            "setId": "032/204\u2022EN\u20221",
            "name": "DINGLEHOPPER",
            "subname": "",
            "ink": "Amber",
            "classification": "Item",
            "rarity": "Common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Eri Welli",
            "description": "STRAIGHTEN HAIR: Remove up to 1 damage from chosen character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_033-204_Lantern.webp",
            "number": "033",
            "setId": "033/204\u2022EN\u20221",
            "name": "LANTERN",
            "subname": "",
            "ink": "Amber",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Eri Welli",
            "description": "BIRTHDAY LIGHTS: You pay 1 cost less for the next character you play this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_034-204_UrsulasShellNecklace.webp",
            "number": "030",
            "setId": "030/204\u2022EN\u20221",
            "name": "URSULAS SHELL NECKLACE",
            "subname": "",
            "ink": "Amber",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Jenna Gray",
            "description": "NOW, SING: Whenever you play a song, you may pay 1 power to draw a card."
        }
    ],
    "firstChapterAmethyst": [
        {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_035-204_Anna-HeirToArendelle.webp",
            "number": "035",
            "setId": "035/204\u2022EN\u20221",
            "name": "ANNA",
            "subname": "Heir to Arendelle",
            "ink": "Amethyst",
            "classification": "Storyborn Hero Queen",
            "rarity": "Uncommon",
            "cost": "4",
            "strength": "2",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Valerio Buonfantino",
            "description": "LOVING HEART: When you play this character, if you have a character named Elsa in play, choose an opposing character. The chosen character doesn't ready at the start of their next turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_036-204_Archimedes-HighlyEducatedOwl.webp",
            "number": "036",
            "setId": "036/204\u2022EN\u20221",
            "name": "ARCHIMEDES",
            "subname": "Highly Educated Owl",
            "ink": "Amethyst",
            "classification": "Dreamborn Ally",
            "rarity": "Common",
            "cost": "1",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Kendall Hale",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_037-204_Dr.Facilier-AgentProvocateur.webp",
            "number": "037",
            "setId": "037/204\u2022EN\u20221",
            "name": "DR. FACILIER",
            "subname": "Agent Provocateur",
            "ink": "Amethyst",
            "classification": "Floodborn Villain Sorcerer",
            "rarity": "Rare",
            "cost": "7",
            "strength": "4",
            "willpower": "5",
            "loreValue": "3",
            "artist": "Isaiah Mesq",
            "description": "INTO THE SHADOWS: Whenever one of your other characters is banished in a challenge, you may return that card to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_038-204_Dr.Facilier-Charlatan.webp",
            "number": "038",
            "setId": "038/204\u2022EN\u20221",
            "name": "DR. FACILIER",
            "subname": "Charlatan",
            "ink": "Amethyst",
            "classification": "Storyborn Villain Sorcerer",
            "rarity": "Common",
            "cost": "2",
            "strength": "0",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Grace Tran",
            "description": "Challenger +2 (While challenging, this character gets +2 strength)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_039-204_Dr.Facilier-RemarkableGentleman.webp",
            "number": "039",
            "setId": "039/204\u2022EN\u20221",
            "name": "DR. FACILIER",
            "subname": "Remarkable Gentleman",
            "ink": "Amethyst",
            "classification": "Storyborn Villain Sorcerer",
            "rarity": "Rare",
            "cost": "3",
            "strength": "2",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Cam Kendell",
            "description": "DREAMS MADE REAL: Whenever you play a song, you may look at the top 2 cards of your deck. Put one on the top of your deck and the other on the bottom."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_040-204_Elsa-QueenRegent.webp",
            "number": "040",
            "setId": "040/204\u2022EN\u20221",
            "name": "ELSA",
            "subname": "Queen Regent",
            "ink": "Amethyst",
            "classification": "Storyborn Hero Queen Sorcerer",
            "rarity": "Common",
            "cost": "4",
            "strength": "4",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Duyen Nguyen / Aubrey Archer",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_041-204_Elsa-SnowQueen.webp",
            "number": "041",
            "setId": "041/204\u2022EN\u20221",
            "name": "ELSA",
            "subname": "Snow Queen",
            "ink": "Amethyst",
            "classification": "Dreamborn Hero Queen Sorcerer",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Nicholas Kole",
            "description": "FREEZE: Exert chosen opposing character"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_042-204_Elsa-SpiritOfWinter.webp",
            "number": "042",
            "setId": "042/204\u2022EN\u20221",
            "name": "ELSA",
            "subname": "Spirit of Winter",
            "ink": "Amethyst",
            "classification": "Floodborn Hero Queen Sorcerer",
            "rarity": "Legendary",
            "cost": "8",
            "strength": "4",
            "willpower": "6",
            "loreValue": "3",
            "artist": "Matthew Robert Davies",
            "description": "DEEP FREEZE: When you play this character, exert up to 2 chosen characters. They can't ready at the start of their next turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_043-204_Flotsam-UrsulasSpy.webp",
            "number": "043",
            "setId": "043/204\u2022EN\u20221",
            "name": "FLOTSAM",
            "subname": "Ursula's Spy",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Rare",
            "cost": "5",
            "strength": "3",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Luis Huerta",
            "description": "DEXTEROUS LUNGE: Your characters named Jetsam gain RUSH (RUSH: This character can challenge the turn they're played)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_044-204_Jafar-KeeperOfSecrets.webp",
            "number": "044",
            "setId": "044/204\u2022EN\u20221",
            "name": "JAFAR",
            "subname": "Keeper of Secrets",
            "ink": "Amethyst",
            "classification": "Dreamborn Villain Sorcerer",
            "rarity": "Rare",
            "cost": "4",
            "strength": "0",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Marcel Berg",
            "description": "HIDDEN WONDERS: This character gets +1 strength for each card in your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_045-204_Jafar-WickedSorcerer.webp",
            "number": "045",
            "setId": "045/204\u2022EN\u20221",
            "name": "JAFAR",
            "subname": "Wicked Sorcerer",
            "ink": "Amethyst",
            "classification": "Dreamborn Villain Sorcerer",
            "rarity": "Common",
            "cost": "4",
            "strength": "2",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Jake Parker",
            "description": "Challenger +3 (While challenging, this character gets +3 strength.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_046-204_Jetsam-UrsulasSpy.webp",
            "number": "046",
            "setId": "046/204\u2022EN\u20221",
            "name": "JETSAM",
            "subname": "Ursula's Spy",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "4",
            "strength": "3",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Brian Weisz",
            "description": "SINISTER SLITHER: Your characters named Flotsam gain Evasive. (EVASIVE: Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_047-204_MagicBroom-BucketBrigade.webp",
            "number": "047",
            "setId": "047/204\u2022EN\u20221",
            "name": "MAGIC BROOM",
            "subname": "Bucket Brigade",
            "ink": "Amethyst",
            "classification": "Dreamborn Boom",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Dav Augereau / Giulia Riva",
            "description": "SWEEP: When you play this character, you may shuffle a card from any discard into its player's deck."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_048-204_Maleficent-BidingHerTime.webp",
            "number": "048",
            "setId": "048/204\u2022EN\u20221",
            "name": "MALEFICENT",
            "subname": "Biding Her Time",
            "ink": "Amethyst",
            "classification": "Dreamborn Villain Sorcerer",
            "rarity": "Rare",
            "cost": "1",
            "strength": "1",
            "willpower": "1",
            "loreValue": "2",
            "artist": "Grace Tran",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_049-204_Maleficent-Sorceress.webp",
            "number": "049",
            "setId": "049/204\u2022EN\u20221",
            "name": "MALEFICENT",
            "subname": "Sorceress",
            "ink": "Amethyst",
            "classification": "Storyborn Villain Sorcerer",
            "rarity": "Common",
            "cost": "3",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Valerio Buonfantino",
            "description": "CAST MY SPELL!: When you play this character, you may draw a card."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_050-204_Marshmallow-PersistentGuardian.webp",
            "number": "050",
            "setId": "050/204\u2022EN\u20221",
            "name": "MARSHMELLOW",
            "subname": "Persistent Guardian",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Super Rare",
            "cost": "6",
            "strength": "5",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Kendall Hale / Anh Dang",
            "description": "DURABLE: When this character is banished in a challenge, you may return this card to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_051-204_MickeyMouse-WaywardSorcerer.webp",
            "number": "051",
            "setId": "051/204\u2022EN\u20221",
            "name": "MICKEY MOUSE",
            "subname": "Wayward Sorcerer",
            "ink": "Amethyst",
            "classification": "Dreamborn Sorcerer",
            "rarity": "Super Rare",
            "cost": "4",
            "strength": "3",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Nicholas Kole",
            "description": "ANIMATE BROOM: You pay 1 cost less to play Brrom characters. CEASLESS WORKER: Whenever oone of your Broom characters is banished in a challenge, you may return that card to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_052-204_Olaf-FriendlySnowman.webp",
            "number": "052",
            "setId": "052/204\u2022EN\u20221",
            "name": "OLAF",
            "subname": "Friendly Snowman",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "1",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Giulia Riva",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_053-204_Pascal-RapunzelsCompanion.webp",
            "number": "053",
            "setId": "053/204\u2022EN\u20221",
            "name": "PASCAL",
            "subname": "Rapunzels Companion",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "1",
            "willpower": "1",
            "loreValue": "1",
            "artist": "Brian Weisz",
            "description": "CAMOUFLAGE: While you have another character in play, this character gains Evasive. (Only characters with Evasive can challenge them.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_054-204_Rafiki-MysteriousSage.webp",
            "number": "054",
            "setId": "054/204\u2022EN\u20221",
            "name": "RAFIKI",
            "subname": "Mysterious Sage",
            "ink": "Amethyst",
            "classification": "Dreamborn Mentor Sorcerer",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "3",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Giulia Riva",
            "description": "RUSH (This character can challenge the turn they're played.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_055-204_Sven-OfficialIceDeliverer.webp",
            "number": "055",
            "setId": "055/204\u2022EN\u20221",
            "name": "SVEN",
            "subname": "Official Ice Deliverer",
            "ink": "Amethyst",
            "classification": "Storyborn Ally",
            "rarity": "Uncommon",
            "cost": "6",
            "strength": "5",
            "willpower": "7",
            "loreValue": "1",
            "artist": "Jared Nickerl",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_056-204_TheQueen-WickedandVain.webp",
            "number": "056",
            "setId": "056/204\u2022EN\u20221",
            "name": "THE QUEEN",
            "subname": "Wicked and Vain",
            "ink": "Amethyst",
            "classification": "Dreamborn Villain Queen",
            "rarity": "Super Rare",
            "cost": "5",
            "strength": "4",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Matthew Robert Davies",
            "description": "I SUMMON THEE: Draw a card."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_057-204_TheWardrobe-BellesConfidant.webp",
            "number": "057",
            "setId": "057/204\u2022EN\u20221",
            "name": "THE WARDROBE",
            "subname": "Belle's Confidant",
            "ink": "Amethyst",
            "classification": "Dreamborn Ally",
            "rarity": "Common",
            "cost": "3",
            "strength": "3",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Giulia Riva",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_058-204_TinkerBell-PeterPansAlly.webp",
            "number": "058",
            "setId": "058/204\u2022EN\u20221",
            "name": "TINKER BELL",
            "subname": "Peter Pan's Ally",
            "ink": "Amethyst",
            "classification": "Storyborn Ally Fairy",
            "rarity": "Common",
            "cost": "5",
            "strength": "3",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Adrianne Gumaya",
            "description": "LOVE AND DEVOTED: Your characters named Peter Pan gain Challenger +1. (They get +1 strength while challenging.) EVASIVE (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_059-204_Ursula-PowerHungry.webp",
            "number": "059",
            "setId": "059/204\u2022EN\u20221",
            "name": "URSULA",
            "subname": "Power Hungry",
            "ink": "Amethyst",
            "classification": "Storyborn Villain Sorcerer",
            "rarity": "Legendary",
            "cost": "7",
            "strength": "2",
            "willpower": "8",
            "loreValue": "3",
            "artist": "Simangaliso Sibaya",
            "description": "IT'S TOO EASY!: When you play this character, each opponent loses 1 lore. You may draw a card for each 1 lore lost this way."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_060-204_Yzma-Alchemist.webp",
            "number": "060",
            "setId": "060/204\u2022EN\u20221",
            "name": "YZMA",
            "subname": "Alchemist",
            "ink": "Amethyst",
            "classification": "Dreamborn Villain Sorcerer",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Hadjie Joos",
            "description": "YOU'RE EXCUSED: Whenever this character quests, look at the top card of your deck. Put it on either the top card of your deck. Put it on either the top or the bottom of your deck."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_061-204_Zeus-GodOfLightning.webp",
            "number": "061",
            "setId": "061/204\u2022EN\u20221",
            "name": "ZEUS",
            "subname": "God of Lightning",
            "ink": "Amethyst",
            "classification": "Storyborn Deity",
            "rarity": "Rare",
            "cost": "4",
            "strength": "0",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Koni",
            "description": "RUSH (This character can challenge the turn they're played.) Challenger +4 (While challenging, this character gets +4 strength.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_062-204_Befuddle.webp",
            "number": "062",
            "setId": "062/204\u2022EN\u20221",
            "name": "BEFUDDLE",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Kendall Hale",
            "description": "Return a character or item with cost 2 or less to their player's hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_063-204_Freeze.webp",
            "number": "063",
            "setId": "063/204\u2022EN\u20221",
            "name": "FREEZE",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Action",
            "rarity": "Common",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Christian Romero",
            "description": "Exert chosen opposing character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_064-204_FriendsOnTheOtherSide.webp",
            "number": "064",
            "setId": "064/204\u2022EN\u20221",
            "name": "FRIENDS ON THE OTHER SIDE",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Action Song",
            "rarity": "Common",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Amber Kommavongsa",
            "description": "Draw 2 cards."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_065-204_Reflection.webp",
            "number": "050",
            "setId": "050/204\u2022EN\u20221",
            "name": "REFLECTION",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Action Song",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Kevin Hong",
            "description": "Look at the top 3 cards of your deck. Put them back on the top of your deck in any order."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_066-204_MagicMirror.webp",
            "number": "066",
            "setId": "066/204\u2022EN\u20221",
            "name": "MAGIC MIRROR",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Andrew Trabbold",
            "description": "SPEAK!: Pay, 4 ink - Draw a card."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_067-204_UrsulasCauldron.webp",
            "number": "067",
            "setId": "067/204\u2022EN\u20221",
            "name": "URSULA'S CAULDRON",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Item",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Oleg Yurkov",
            "description": "PEER INTO THE DEPTHS: Look at the top 2 cards of your deck. Put one on the top of your deck and the other on the bottom."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_068-204_WhiteRabbitsPocketWatch.webp",
            "number": "068",
            "setId": "068/204\u2022EN\u20221",
            "name": "WHITE RABBIT'S POCKET WATCH",
            "subname": "",
            "ink": "Amethyst",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Kamil Murzyn",
            "description": "I'M LATE!: Pay, 1 ink - Chosen character gains Rush this turn. (They can challenge the turn they're played.)"
        },
    ],
    "firstChapterEmerald": [
        {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_069-204_Aladdin-PrinceAli.webp",
            "number": "069",
            "setId": "069/204\u2022EN\u20221",
            "name": "ALADDIN",
            "subname": "Prince Ali",
            "ink": "Emerald",
            "classification": "Storyborn Hero Prince",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Lauren Walsh",
            "description": "WARD (Opponents can't choose this character execpt to challenge.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_070-204_Beast-Wolfsbane.webp",
            "number": "070",
            "setId": "070/204\u2022EN\u20221",
            "name": "BEAST",
            "subname": "Wolfsbane",
            "ink": "Emerald",
            "classification": "Dreamborn Hero Prince",
            "rarity": "Legendary",
            "cost": "5",
            "strength": "4",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Jeff Murchie",
            "description": "ROAR: When you play this character, exert all opposing damaged characters. RUSH (This character can challenge the turn they're played)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_071-204_CheshireCat-NotAllThere.webp",
            "number": "071",
            "setId": "071/204\u2022EN\u20221",
            "name": "CHESHIRE CAT",
            "subname": "Not All There",
            "ink": "Emerald",
            "classification": "Storyborn",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "0",
            "willpower": "3",
            "loreValue": "2",
            "artist": "Caner Soylu",
            "description": "LOOSE SOMETHING?: When this character is challenged and banished, banish the challenging character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_072-204_CruellaDeVil-MiserableAsUsual.webp",
            "number": "072",
            "setId": "072/204\u2022EN\u20221",
            "name": "CRUELLA DE VIL",
            "subname": "Miserable as Usual",
            "ink": "Emerald",
            "classification": "Storyborn Villain",
            "rarity": "Rare",
            "cost": "2",
            "strength": "1",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Nicholas Kole",
            "description": "YOU'LL BE SORRY!: When this character is challenged and banished, you may return chosen character to their player's hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_073-204_DukeOfWeselton-OpportunisticOfficial.webp",
            "number": "073",
            "setId": "073/204\u2022EN\u20221",
            "name": "DUKE OF WESELTON",
            "subname": "Opportunistic Official",
            "ink": "Emerald",
            "classification": "Storyborn Villain",
            "rarity": "Common",
            "cost": "1",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "R. La Barbera / L. Giammichele",
            "description": ""
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_074-204_FlynnRider-CharmingRogue.webp\" alt=\"Flynn Rider: Charming Rogue",
            "number": "074",
            "setId": "074/204\u2022EN\u20221",
            "name": "FLYNN RIDER",
            "subname": "Charming Rogue",
            "ink": "Emerald",
            "classification": "Storyborn Hero Prince",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "1",
            "willpower": "2",
            "loreValue": "2",
            "artist": "Leonardo Giammichele",
            "description": "HERE COMES THE SMOLDER: Whanever this character is challenged, the  challenging player chooses and discards a card."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_075-204_Genie-OntheJob.webp\" alt=\"Genie: On the Job",
            "number": "075",
            "setId": "075/204\u2022EN\u20221",
            "name": "GENIE",
            "subname": "On the Job",
            "ink": "Emerald",
            "classification": "Storyborn Ally",
            "rarity": "Super Rare",
            "cost": "6",
            "strength": "3",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Giulia Riva",
            "description": "DISAPPEAR: When you play this character, you may return chosen character to their player's hand. EVASIVE (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_076-204_Genie-PowersUnleashed.webp\" alt=\"Genie: Powers Unleashed",
            "number": "076",
            "setId": "076/204\u2022EN\u20221",
            "name": "GENIE",
            "subname": "Powers Unleashed",
            "ink": "Emerald",
            "classification": "Floodborn Hero",
            "rarity": "Rare",
            "cost": "8",
            "strength": "3",
            "willpower": "5",
            "loreValue": "3",
            "artist": "Javier Salas",
            "description": "PHENOMENAL COSMIC POWER!: Whenever this character quests, you play an action with cost 5 or less for free. EVASIVE (Only characters with Evasive can challenge this character.) SHIFT 6 (You may pay 6 ink to play this on top of one of your characters named Genie.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_077-204_Genie-TheEverImpressive.webp\" alt=\"Genie: The Ever Impressive",
            "number": "077",
            "setId": "077/204\u2022EN\u20221",
            "name": "GENIE",
            "subname": "The Ever Impressive",
            "ink": "Emerald",
            "classification": "Dreamborn Ally",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Matt Chapman",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/Lorcanach1_078-204_Hans-SchemingPrince.webp\" alt=\"Hans: Scheming Prince",
            "number": "078",
            "setId": "078/204\u2022EN\u20221",
            "name": "HANS",
            "subname": "Scheming Prince",
            "ink": "Emerald",
            "classification": "Storyborn Villain Prince",
            "rarity": "Rare",
            "cost": "4",
            "strength": "3",
            "willpower": "3",
            "loreValue": "3",
            "artist": "Massimiliano Narciso",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_079-204_Horace-NoGoodScoundrel.webp\" alt=\"Horace: No Good Scoundrel",
            "number": "079",
            "setId": "079/204\u2022EN\u20221",
            "name": "HORACE",
            "subname": "No-Good Scoundrel",
            "ink": "Emerald",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "3",
            "strength": "4",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Isaiah Masq",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_080-204_Iago-LoudMouthedParrot.webp\" alt=\"Iago: Loud Mouthed Parrot",
            "number": "080",
            "setId": "080/204\u2022EN\u20221",
            "name": "IAGO",
            "subname": "Load-Mouthed Parrot",
            "ink": "Emerald",
            "classification": "Storyborn Ally",
            "rarity": "Rare",
            "cost": "3",
            "strength": "1",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Brian Weisz",
            "description": "YOU GOT A PROBLEM?: Chosen character gains Reckless during their next turn. (They can't quest and must challenge if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_081-204_Jasper-CommonCrook.webp\" alt=\"Jasper: Common Crook",
            "number": "081",
            "setId": "081/204\u2022EN\u20221",
            "name": "JASPER",
            "subname": "Common Crook",
            "ink": "Emerald",
            "classification": "Storyborn Ally",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "2",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Jochem Van Gool",
            "description": "PUPPYNAPPING: Whenever this character quests, chosen opposing character can't quest during their next turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_082-204_JohnSilver-AlienPirate.webp\" alt=\"John Silver: Alien Pirate",
            "number": "082",
            "setId": "082/204\u2022EN\u20221",
            "name": "JOHN SILVER",
            "subname": "Alien Pirate",
            "ink": "Emerald",
            "classification": "Storyborn Villain Alien Pirate Captain",
            "rarity": "Legendary",
            "cost": "6",
            "strength": "5",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Duyen Nguyen / Jared Nickeri",
            "description": "PICK YOUR FIGHTS: When you play this character and whenever he quests, chosen opposing character gains Reckless during their next turn. (They can't quest and must challenge if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_083-204_JumbaJookiba-RenegadeScientist.webp\" alt=\"Jumba Jookiba: Renegade Scientist",
            "number": "083",
            "setId": "083/204\u2022EN\u20221",
            "name": "JUMBA JOOKIBA",
            "subname": "Renegade Scientist",
            "ink": "Emerald",
            "classification": "Dreamborn Alien Inventor",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "4",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Milica Celikovic",
            "description": ""
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_084-204_Kuzco-TemperamentalEmperor.webp\" alt=\"Kuzco: Temperamental Emperor",
            "number": "084",
            "setId": "084/204\u2022EN\u20221",
            "name": "KUZCO",
            "subname": "Temperamental Emperor",
            "ink": "Emerald",
            "classification": "Storyborn King",
            "rarity": "Rare",
            "cost": "5",
            "strength": "2",
            "willpower": "4",
            "loreValue": "3",
            "artist": "Grace Tran",
            "description": "NO TOUCHY!: When this character is challenged and banished, you may banish the challenging character. WARD (Opponents can't choose this character except to challenge.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_085-204_LadyTremaine-WickedStepmother.webp\" alt=\"Lady Tremaine: Wicked Stepmother",
            "number": "085",
            "setId": "085/204\u2022EN\u20221",
            "name": "LADY TERMAINE",
            "subname": "Wicked Stepmother",
            "ink": "Emerald",
            "classification": "Dreamborn Villain",
            "rarity": "Rare",
            "cost": "6",
            "strength": "1",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Leonardo Giammichele",
            "description": "DO IT AGAIN!: When you play this character, you may return an action card from your discard to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_086-204_MadHatter-GraciousHost.webp\" alt=\"Mad Hatter: Gracious Host",
            "number": "086",
            "setId": "086/204\u2022EN\u20221",
            "name": "MAD HATTER",
            "subname": "Gracious Host",
            "ink": "Emerald",
            "classification": "Storyborn",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "2",
            "willpower": "4",
            "loreValue": "3",
            "artist": "Rosa la Barbera",
            "description": "TEA PARTY: Whenever this character is challenged, you may draw a card."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_087-204_Megara-PullingTheStrings.webp\" alt=\"Megara: Pulling The Strings",
            "number": "087",
            "setId": "087/204\u2022EN\u20221",
            "name": "MEGARA",
            "subname": "Pulling the Strings",
            "ink": "Emerald",
            "classification": "Dreamborn Ally",
            "rarity": "Common",
            "cost": "2",
            "strength": "2",
            "willpower": "1",
            "loreValue": "1",
            "artist": "Aubrey Archer",
            "description": "WONDER BOY: When you play this character, chosen character gets +2 strength this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_088-204_MickeyMouse-ArtfulRogue.webp\" alt=\"Mickey Mouse: Artful Rogue",
            "number": "088",
            "setId": "088/204\u2022EN\u20221",
            "name": "MICKEY MOUSE",
            "subname": "Artful Rogue",
            "ink": "Emerald",
            "classification": "Floodborn Hero",
            "rarity": "Super Rare",
            "cost": "7",
            "strength": "6",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Alex Accorsi / Kendall Hale",
            "description": "MISDIRECTION: When you play an action, chosen opposing character can't quest during their next turn. SHIFT 5 (You may pay 5 ink to play this on top of one of your characters named Mickey Mouse.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_089-204_MickeyMouse-SteamboatPilot.webp\" alt=\"Mickey Mouse: Steamboat Pilot",
            "number": "089",
            "setId": "089/204\u2022EN\u20221",
            "name": "MICKEY MOUSE",
            "subname": "Steamboat Pilot",
            "ink": "Emerald",
            "classification": "Storyborn Hero Captain",
            "rarity": "Common",
            "cost": "3",
            "strength": "3",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Juan Diego Leon",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_090-204_MotherGothel-SelfishManipulator.webp\" alt=\"Mother Gothel: Selfish Manipulator",
            "number": "090",
            "setId": "090/204\u2022EN\u20221",
            "name": "MOTHER GOTHEL",
            "subname": "Shelfish Manipulator",
            "ink": "Emerald",
            "classification": "Storyborn Villain",
            "rarity": "Super Rare",
            "cost": "6",
            "strength": "3",
            "willpower": "6",
            "loreValue": "2",
            "artist": "Javier Salas",
            "description": "SKIP THE DRAMA, STAY WITH MAMMA: While this character is exerted, opposing characters can't quest."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_091-204_PeterPan-NeverLanding.webp\" alt=\"Peter Pan: Never Landing",
            "number": "091",
            "setId": "091/204\u2022EN\u20221",
            "name": "PETER PAN",
            "subname": "Never Landing",
            "ink": "Emerald",
            "classification": "Dreamborn Hero",
            "rarity": "Common",
            "cost": "3",
            "strength": "3",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Koni",
            "description": "EVASIVE (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_092-204_Tamatoa-DrabLittleCrab.webp\" alt=\"Tamatoa: Drab Little Crab",
            "number": "092",
            "setId": "092/204\u2022EN\u20221",
            "name": "TAMATOA",
            "subname": "Drab Little Crab",
            "ink": "Emerald",
            "classification": "Dreamborn",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "1",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Jeff Murchie",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_093-204_TinkerBell-MostHelpful.webp\" alt=\"Tinkerbell: Most Helpful",
            "number": "093",
            "setId": "093/204\u2022EN\u20221",
            "name": "TINKER BELL",
            "subname": "Most Helpful",
            "ink": "Emerald",
            "classification": "Storyborn Ally Fairy",
            "rarity": "Common",
            "cost": "4",
            "strength": '"2',
            "willpower": "3",
            "loreValue": "2",
            "artist": "Caner Soylu",
            "description": "PIXIE DUST: When you play this character, chosen character gains Evasive this turn. EVASIVE (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_094-204_DoItAgain.webp\" alt=\"Do It Again",
            "number": "094",
            "setId": "094/204\u2022EN\u20221",
            "name": "DO IT AGAIN!",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Ellie Horie",
            "description": "Return an action card from your discard to your hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_095-204_MotherKnowsBest.webp\" alt=\"Mother Knows Best",
            "number": "095",
            "setId": "095/204\u2022EN\u20221",
            "name": "MOTHER KNOWS BEST",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action Song",
            "rarity": "Uncommon",
            "cost": "",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "R. La Barbera / L. Giammichele",
            "description": "Return chosen character to their player's hand."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_096-204_Stampede.webp\" alt=\"Stampede",
            "number": "096",
            "setId": "096/204\u2022EN\u20221",
            "name": "STAMPEDE",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action",
            "rarity": "Common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Matt Chapman",
            "description": "Deal 2 damage to chosen damaged character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_097-204_StealFromTheRich.webp\" alt=\"Steal From The Rich",
            "number": "097",
            "setId": "097/204\u2022EN\u20221",
            "name": "STEAL FROM THE RICH",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action",
            "rarity": "Rare",
            "cost": "5",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Hedvig Haggman-Sund",
            "description": "Whenever one of your characters quests this turn, each opponent loses 1 lore."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_098-204_SuddenChill.webp\" alt=\"Sudden Chill",
            "number": "098",
            "setId": "098/204\u2022EN\u20221",
            "name": "SUDDEN CHILL",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action Song",
            "rarity": "Common",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Giulia Riva",
            "description": "Each opponent chooses and discards a card."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_099-204_TheBeastIsMine.webp\" alt=\"The Beast Is Mine",
            "number": "099",
            "setId": "099/204\u2022EN\u20221",
            "name": "THE BEAST IS MINE",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Matthew Robert Davies",
            "description": "Chosen character gains Reckless during their next turn. (They can't quest and must challange if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_100-204_ViciousBetrayal.webp\" alt=\"Vicious Betrayal",
            "number": "100",
            "setId": "100/204\u2022EN\u20221",
            "name": "VICIOUS BETRAYAL",
            "subname": "",
            "ink": "Emerald",
            "classification": "Action",
            "rarity": "Common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Michaela Martin",
            "description": "Chosen character gets +2 strength this turm. If a Villain character is chosen, they get +3 strength instead."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_101-204_Dr.FaciliersCards.webp\" alt=\"Dr. Facilier's Cards",
            "number": "101",
            "setId": "101/204\u2022EN\u20221",
            "name": "DR. FACILIER'S CARDS",
            "subname": "",
            "ink": "Emerald",
            "classification": "Item",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Koni",
            "description": "THE CARDS WILL TELL: You pay 1 ink less for the next action you play this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_102-204_StolenScimitar.webp\" alt=\"Stolen Scimitar",
            "number": "102",
            "setId": "102/204\u2022EN\u20221",
            "name": "STOLEN SCIMITAR",
            "subname": "",
            "ink": "Emerald",
            "classification": "Item",
            "rarity": "Common",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Kendall Hale",
            "description": "SLASH: Chosen character gets +1 strength this turn. If a character named Aladdin is chosen, he gets +2 strength instead.)"
        },
    ],
    "firstChapterRuby": [
        {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_103-204_Abu-MischievousMonkey.webp\" alt=\"Abu: Mischievous Monkey",
            "number": "103",
            "setId": "103/204\u2022EN\u20221",
            "name": "ABU",
            "subname": "Mischievous Monkey",
            "ink": "Ruby",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "3",
            "strength": "3",
            "willpower": "2",
            "loreValue": "2",
            "artist": "Oleg Yurkov",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_104-204_Aladdin-HeroicOutlaw.webp\" alt=\"Aladdin: Hero Outlaw",
            "number": "104",
            "setId": "104/204\u2022EN\u20221",
            "name": "ALADDIN",
            "subname": "Heroic Outlaw",
            "ink": "Ruby",
            "classification": "Floodborn Hero",
            "rarity": "Super Rare",
            "cost": "7",
            "strength": "5",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Nicholas Kole",
            "description": "DARING EXPLOIT: During your turn, whenever this character banishes another character in a challenge, you gain 2 lore and each opponent loses 2 lore."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_105-204_Aladdin-StreetRat.webp\" alt=\"Aladdin: Street Rat",
            "number": "105",
            "setId": "105/204\u2022EN\u20221",
            "name": "ALADDIN",
            "subname": "Street Rat",
            "ink": "Ruby",
            "classification": "Storyborn Hero",
            "rarity": "Common",
            "cost": "3",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Peter Brockhammer",
            "description": "IMPROVISE: When you play this character, each opponent loses 1 lore."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_106-204_Captain-ColonelsLieutenant.webp\" alt=\"Captain: Colonels Lieutenant",
            "number": "106",
            "setId": "106/204\u2022EN\u20221",
            "name": "CAPTAIN",
            "subname": "Colonels Lieutenant",
            "ink": "Ruby",
            "classification": "Storyborn Ally Captain",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "6",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Brian Weisz",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_107-204_CaptainHook-RuthlessPirate.webp\" alt=\"Captain Hook: Ruthless Pirate",
            "number": "107",
            "setId": "107/204\u2022EN\u20221",
            "name": "CAPTAIN HOOK",
            "subname": "Ruthless Pirate",
            "ink": "Ruby",
            "classification": "Storyborn Villain Pirate Captain",
            "rarity": "Rare",
            "cost": "7",
            "strength": "5",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Cam Kendell",
            "description": "YOU COWARD!: When this character is exerted, opposing characters with Evasive gain Reckless. (They can't quest and must challenge if able.)"
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_108-204_DonaldDuck-BoisterousFowl.webp\" alt=\"Donald Duck: Boisterous Fowl",
            "number": "108",
            "setId": "108/204\u2022EN\u20221",
            "name": "DONALD DUCK",
            "subname": "Boisterous Fowl",
            "ink": "Ruby",
            "classification": "Storyborn",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "2",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Kenneth Anderson",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_109-204_Elsa-IceSurfer.webp\" alt=\"Els: Ice Surfer",
            "number": "109",
            "setId": "109/204\u2022EN\u20221",
            "name": "ELSA",
            "subname": "On the Job",
            "ink": "Ruby",
            "classification": "Dreamborn Hero Queen Sorcerer",
            "rarity": "Common",
            "cost": "4",
            "strength": "3",
            "willpower": "4",
            "loreValue": "1",
            "artist": "Alice Pisoni / Whitney Pollett",
            "description": "THAT'S NO BLIZZARD: Whenever you play a character named Anna, ready this character. This character can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_110-204_Gaston-ArrogantHunter.webp\" alt=\"Gaston: Arrogant Hunter",
            "number": "110",
            "setId": "110/204\u2022EN\u20221",
            "name": "GASTON",
            "subname": "Arrogant Hunter",
            "ink": "Ruby",
            "classification": "Storyborn Villain",
            "rarity": "Common",
            "cost": "2",
            "strength": "4",
            "willpower": "2",
            "loreValue": "",
            "artist": "Matthew Robert Davies",
            "description": "RECKLESS (This character can't quest and must challenge each turn if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_111-204_Goofy-Daredevil.webp\" alt=\"Goofy: Daredevil",
            "number": "111",
            "setId": "111/204\u2022EN\u20221",
            "name": "GOOFY",
            "subname": "Daredevil",
            "ink": "Ruby",
            "classification": "Dreamborn Hero",
            "rarity": "Common",
            "cost": "5",
            "strength": "3",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Kenneth Anderson",
            "description": "EVASIVE (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_112-204_Lefou-Instigator.webp\" alt=\"Lefou: Instigator",
            "number": "112",
            "setId": "112/204\u2022EN\u20221",
            "name": "LEFOU",
            "subname": "Instigator",
            "ink": "Ruby",
            "classification": "Dreamborn Ally",
            "rarity": "Rare",
            "cost": "2",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Gaku Kumatori",
            "description": "FAN THE FLAMES: When you play this characer, ready chosen character. They can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_113-204_Maleficent-MonstrousDragon.webp\" alt=\"Maleficent: Monstrous Dragon",
            "number": "113",
            "setId": "113/204\u2022EN\u20221",
            "name": "MALEFICENT",
            "subname": "Monstrous Dragon",
            "ink": "Ruby",
            "classification": "Storyborn Villain Dragon",
            "rarity": "Legendary",
            "cost": "9",
            "strength": "7",
            "willpower": "5",
            "loreValue": "2",
            "artist": "Luis Huerta",
            "description": "DRAGON FIRE: When you play this character, you may banish chosen character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_114-204_Maui-HeroToAll.webp\" alt=\"Maui: Hero to All",
            "number": "114",
            "setId": "114/204\u2022EN\u20221",
            "name": "MAUI",
            "subname": "Hero to All",
            "ink": "Ruby",
            "classification": "Storyborn Hero Deity",
            "rarity": "Rare",
            "cost": "5",
            "strength": "6",
            "willpower": "5",
            "loreValue": "",
            "artist": "Pirel / Marco Giogianni",
            "description": "Rush (This character can challenge the turn they're played.) Reckless (This character can't quest and must challenge each turn if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_115-204_MickeyMouse-BraveLittleTailor.webp\" alt=\"Mickey Mouse: Brave Little Tailor",
            "number": "115",
            "setId": "115/204\u2022EN\u20221",
            "name": "MICKEY MOUSE",
            "subname": "Brave Little Tailor",
            "ink": "Ruby",
            "classification": "Dreamborn Hero",
            "rarity": "Legendary",
            "cost": "8",
            "strength": "5",
            "willpower": "5",
            "loreValue": "4",
            "artist": "Nicholas Kole",
            "description": "Evasive (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_116-204_MinnieMouse-AlwaysClassy.webp\" alt=\"Minnie Mouse: Always Classy",
            "number": "116",
            "setId": "116/204\u2022EN\u20221",
            "name": "MINNIE MOUSE",
            "subname": "Always Classy",
            "ink": "Ruby",
            "classification": "Storyborn Hero",
            "rarity": "Common",
            "cost": "1",
            "strength": "1",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Kenneth Anderson",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_117-204_Moana-ChosenByTheOcean.webp\" alt=\"Moana: Chosen By The Ocean",
            "number": "117",
            "setId": "117/204\u2022EN\u20221",
            "name": "MOANA",
            "subname": "Chosen By The Ocean",
            "ink": "Ruby",
            "classification": "Storyborn Hero Princess",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "2",
            "willpower": "6",
            "loreValue": "2",
            "artist": "Tanisha Cherislin",
            "description": "THIS IS NOT WHO YOU ARE: When you play this character, you may banish chosen character named Te Ka."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_118-204_Mulan-ImperialSoldier.webp\" alt=\"Mulan: Imperial Soldier",
            "number": "118",
            "setId": "118/204\u2022EN\u20221",
            "name": "MULAN",
            "subname": "Imperial Soldier",
            "ink": "Ruby",
            "classification": "Storyborn Hero Princess",
            "rarity": "Super Rare",
            "cost": "5",
            "strength": "4",
            "willpower": "5",
            "loreValue": "1",
            "artist": "Mel Milton",
            "description": "LEAD BY EXAMPLE: During your turn, whenever this character banishes another character in a challenge, your other characters get +1 lore this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_119-204_PeterPan-FearlessFighter.webp\" alt=\"Peter Pan: Fearless Fighter",
            "number": "119",
            "setId": "119/204\u2022EN\u20221",
            "name": "PETER PAN",
            "subname": "Fearless Fighter",
            "ink": "Ruby",
            "classification": "Storyborn Hero",
            "rarity": "Common",
            "cost": "3",
            "strength": "3",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Anh Dang",
            "description": "Rush (This character can challenge the turn they're played.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_120-204_Pongo-OlRascal.webp\" alt=\"Pongo: Ol Rascal",
            "number": "120",
            "setId": "120/204\u2022EN\u20221",
            "name": "PONGO",
            "subname": "Ol Rascal",
            "ink": "Ruby",
            "classification": "Storyborn Hero",
            "rarity": "Common",
            "cost": "4",
            "strength": "2",
            "willpower": "3",
            "loreValue": "2",
            "artist": "Brian Weisz",
            "description": "Evasive (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_121-204_Rapunzel-LettingDownHerHair.webp\" alt=\"Rapunzel: Letting Down Her Hair",
            "number": "121",
            "setId": "121/204\u2022EN\u20221",
            "name": "RAPUNZEL",
            "subname": "Letting Down Her Hair",
            "ink": "Ruby",
            "classification": "Dreamborn Hero Princess",
            "rarity": "Uncommon",
            "cost": "6",
            "strength": "5",
            "willpower": "4",
            "loreValue": "2",
            "artist": "Clio Wolfensberger",
            "description": "TANGLE: When you play this character, each opponent loses 1 lore."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_122-204_Scar-FieryUsurper.webp\" alt=\"Scar: Fiery Usurper",
            "number": "122",
            "setId": "122/204\u2022EN\u20221",
            "name": "SCAR",
            "subname": "Fiery Usurper",
            "ink": "Ruby",
            "classification": "Dreamborn Villain",
            "rarity": "Common",
            "cost": "4",
            "strength": "5",
            "willpower": "3",
            "loreValue": "1",
            "artist": "Amber Kommavongsa",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_123-204_Scar-ShamelessFirebrand.webp\" alt=\"Scar: Shameless Firebrand",
            "number": "123",
            "setId": "123/204\u2022EN\u20221",
            "name": "SCAR",
            "subname": "Shameless Firebrand",
            "ink": "Ruby",
            "classification": "Floodborn Villain King",
            "rarity": "Rare",
            "cost": "8",
            "strength": "6",
            "willpower": "6",
            "loreValue": "1",
            "artist": "Jenna Gray",
            "description": "ROUSING SPEECH: When you play this character, ready your characters with cost 3 or less. They can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_124-204_SergeantTibbs-CourageousCat.webp\" alt=\"Sergeant Tibbs: Courageous Cat",
            "number": "124",
            "setId": "124/204\u2022EN\u20221",
            "name": "SERGEANT TIBBS",
            "subname": "Courageous Cat",
            "ink": "Ruby",
            "classification": "Storyborn Ally",
            "rarity": "Common",
            "cost": "1",
            "strength": "2",
            "willpower": "2",
            "loreValue": "1",
            "artist": "Cory Godbey",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_125-204_Stitch-Abomination.webp\" alt=\"Stitch: Abomination",
            "number": "125",
            "setId": "125/204\u2022EN\u20221",
            "name": "STITCH",
            "subname": "Abomination",
            "ink": "Ruby",
            "classification": "Storyborn Hero Alien",
            "rarity": "Rare",
            "cost": "6",
            "strength": "4",
            "willpower": "6",
            "loreValue": "3",
            "artist": "Bill Robinson",
            "description": ""
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_126-204_TeKa-TheBurningOne.webp\" alt=\"TeKa: The Burning One",
            "number": "126",
            "setId": "092/204\u2022EN\u20221",
            "name": "TE KA",
            "subname": "The Burning One",
            "ink": "Ruby",
            "classification": "Storyborn Villain Deity",
            "rarity": "Super Rare",
            "cost": "6",
            "strength": "8",
            "willpower": "6",
            "loreValue": "",
            "artist": "Kamil Murzyn",
            "description": "Reckless (This character can't quest and must challenge each turn if able.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_127-204_Tigger-WonderfulThing.webp\" alt=\"Tigger: Wonderful Thing",
            "number": "127",
            "setId": "127/204\u2022EN\u20221",
            "name": "TIGGER",
            "subname": "Wonderful Thing",
            "ink": "Ruby",
            "classification": "Storyborn Tigger",
            "rarity": "Uncommon",
            "cost": "6",
            "strength": '"4',
            "willpower": "4",
            "loreValue": "2",
            "artist": "Kenneth Anderson",
            "description": "Evasive (Only characters with Evasive can challenge this character.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_128-204_BePrepared.webp\" alt=\"Be Prepared",
            "number": "128",
            "setId": "128/204\u2022EN\u20221",
            "name": "BE PREPARED",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action Song",
            "rarity": "Rare",
            "cost": "7",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Jared Nickeri",
            "description": "Banish all characters."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_129-204_CutToTheChase.webp\" alt=\"Cut To The Chase",
            "number": "129",
            "setId": "129/204\u2022EN\u20221",
            "name": "CUT TO THE CHASE",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Ellie Horie",
            "description": "Chosen character gets Rush this turn. (They can challenge the turn they're played.)"
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_130-204_DragonFire.webp\" alt=\"Dragon Fire",
            "number": "130",
            "setId": "130/204\u2022EN\u20221",
            "name": "DRAGON FIRE",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "5",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Luis Huerta",
            "description": "Banish chosen character."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_131-204_FanTheFlames.webp\" alt=\"Fan The Flames",
            "number": "131",
            "setId": "131/204\u2022EN\u20221",
            "name": "FAN THE FLAMES",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Jenna Gray",
            "description": "Ready chosen character. They can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_132-204_HesGotASword.webp\" alt=\"He's Got A Sword",
            "number": "132",
            "setId": "132/204\u2022EN\u20221",
            "name": "HE'S GOT A SWORD",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action",
            "rarity": "Common",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Koni",
            "description": "Chosen character gets +2 strength this turn."
        },{
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_133-204_Tangle.webp\" alt=\"Tangle",
            "number": "133",
            "setId": "133/204\u2022EN\u20221",
            "name": "TANGLE",
            "subname": "",
            "ink": "Ruby",
            "classification": "Action",
            "rarity": "Common",
            "cost": "2",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Eri Welli",
            "description": "Each opponent loses 1 lore."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_134-204_PoisonedApple.webp\" alt=\"Poisoned Apple",
            "number": "134",
            "setId": "134/204\u2022EN\u20221",
            "name": "POISONED APPLE",
            "subname": "",
            "ink": "Ruby",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "3",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Andrew Trabbold",
            "description": "TAKE A BITE...: 1 ink, Banish this item - Exert chosen character. If a Princess character is chosen, banish her instead."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_135-204_ShieldOfVirtue.webp\" alt=\"Shield Of Virtue",
            "number": "135",
            "setId": "135/204\u2022EN\u20221",
            "name": "SHEILD OF VIRTUE",
            "subname": "",
            "ink": "Ruby",
            "classification": "Item",
            "rarity": "Uncommon",
            "cost": "1",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Eri Welli",
            "description": "FIREPROOF: 3 ink - Ready chosen character. They can't quest for the rest of this turn."
        }, {
            "cardImg": "../media/LorcanaCh1/LorcanaCh1_136-204_SwordOfTruth.webp\" alt=\"Sword Of Truth",
            "number": "136",
            "setId": "136/204\u2022EN\u20221",
            "name": "SWORD OF TRUTH",
            "subname": "",
            "ink": "Ruby",
            "classification": "Item",
            "rarity": "Rare",
            "cost": "24",
            "strength": "",
            "willpower": "",
            "loreValue": "",
            "artist": "Kendall Hale",
            "description": "FINAL ENCHANTMENT: Banish this item - Banish chosen Villain character."
        },
    ],

}

function lorcanaCardData() {
    // console.log(lorcanadb.firstChapter)
    var firstChapterAmber = lorcanadb.firstChapterAmber;
        $.each(firstChapterAmber, function(i, val) {
            var cardImg = val.cardImg
            var number = val.number;
            var setId = val.setId;
            var name = val.name;
            var subname = val.subname;
            var ink = val.ink;
            var classification = val.classification;
            var rarity = val.rarity;
            var cost = val.cost;
            var strength = val.strength;
            var willpower = val.willpower;
            var loreValue = val.loreValue;
            var artist = val.artist;
            var description = val.description;

            $('.cardContainer1').append('    <div class="cardSingleJSON">' +
                '                <h3 class="cardTitleGold">'+name+'</h3>\n' +
                '                <p class="cardTitleGold">'+subname+'</p>\n' +
                '                <div class="cardCenter">\n' +
                '                    <img src="' + cardImg + '" alt="' + name + ' ' + subname + '">' +
                '                    <div class="cardSelectors">\n' +
                '                        <form action="#" method="POST" class="cardForm">\n' +
                '                            <label for="en_1_base_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText1">Base</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_base_001/204" value="Base-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                            <label for="en_1_foil_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText2" style="margin-left: 20px;">Foil</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_foil_001/204" value="Foil-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                        </form>\n' +
                '                    </div>\n' +
                '                </div>\n' +
                '                <h3 class="cardID">'+setId+'</h3>\n' +
                '           </div>')

        });

    var firstChapterAmethyst = lorcanadb.firstChapterAmethyst;
        $.each(firstChapterAmethyst, function(i, val) {
            var cardImg = val.cardImg
            var number = val.number;
            var setId = val.setId;
            var name = val.name;
            var subname = val.subname;
            var ink = val.ink;
            var classification = val.classification;
            var rarity = val.rarity;
            var cost = val.cost;
            var strength = val.strength;
            var willpower = val.willpower;
            var loreValue = val.loreValue;
            var artist = val.artist;
            var description = val.description;

            $('.cardContainer2').append('    <div class="cardSingleJSON">' +
                '                <h3 class="cardTitleGold">'+name+'</h3>\n' +
                '                <p class="cardTitleGold">'+subname+'</p>\n' +
                '                <div class="cardCenter">\n' +
                '                    <img src="' + cardImg + '" alt="' + name + ' ' + subname + '">' +
                '                    <div class="cardSelectors">\n' +
                '                        <form action="#" method="POST" class="cardForm">\n' +
                '                            <label for="en_1_base_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText1">Base</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_base_001/204" value="Base-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                            <label for="en_1_foil_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText2" style="margin-left: 20px;">Foil</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_foil_001/204" value="Foil-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                        </form>\n' +
                '                    </div>\n' +
                '                </div>\n' +
                '                <h3 class="cardID">'+setId+'</h3>\n' +
                '           </div>')

        });

    var firstChapterEmerald = lorcanadb.firstChapterEmerald;
        $.each(firstChapterEmerald, function(i, val) {
            var cardImg = val.cardImg
            var number = val.number;
            var setId = val.setId;
            var name = val.name;
            var subname = val.subname;
            var ink = val.ink;
            var classification = val.classification;
            var rarity = val.rarity;
            var cost = val.cost;
            var strength = val.strength;
            var willpower = val.willpower;
            var loreValue = val.loreValue;
            var artist = val.artist;
            var description = val.description;

            $('.cardContainer3').append('    <div class="cardSingleJSON">' +
                '                <h3 class="cardTitleGold">'+name+'</h3>\n' +
                '                <p class="cardTitleGold">'+subname+'</p>\n' +
                '                <div class="cardCenter">\n' +
                '                    <img src="' + cardImg + '" alt="' + name + ' ' + subname + '">' +
                '                    <div class="cardSelectors">\n' +
                '                        <form action="#" method="POST" class="cardForm">\n' +
                '                            <label for="en_1_base_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText1">Base</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_base_001/204" value="Base-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                            <label for="en_1_foil_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText2" style="margin-left: 20px;">Foil</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_foil_001/204" value="Foil-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                        </form>\n' +
                '                    </div>\n' +
                '                </div>\n' +
                '                <h3 class="cardID">'+setId+'</h3>\n' +
                '           </div>')

        });

    var firstChapterRuby = lorcanadb.firstChapterRuby;
        $.each(firstChapterRuby, function(i, val) {
            var cardImg = val.cardImg
            var number = val.number;
            var setId = val.setId;
            var name = val.name;
            var subname = val.subname;
            var ink = val.ink;
            var classification = val.classification;
            var rarity = val.rarity;
            var cost = val.cost;
            var strength = val.strength;
            var willpower = val.willpower;
            var loreValue = val.loreValue;
            var artist = val.artist;
            var description = val.description;

            $('.cardContainer4').append('    <div class="cardSingleJSON">' +
                '                <h3 class="cardTitleGold">'+name+'</h3>\n' +
                '                <p class="cardTitleGold">'+subname+'</p>\n' +
                '                <div class="cardCenter">\n' +
                '                    <img src="' + cardImg + '" alt="' + name + ' ' + subname + '">' +
                '                    <div class="cardSelectors">\n' +
                '                        <form action="#" method="POST" class="cardForm">\n' +
                '                            <label for="en_1_base_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText1">Base</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_base_001/204" value="Base-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                            <label for="en_1_foil_001/204" style="writing-mode: horizontal-tb;"><span class="cardLabelText2" style="margin-left: 20px;">Foil</span>\n' +
                '                                <input type="checkbox" name="card" id="en_1_foil_001/204" value="Foil-EN-1-1/204" class="cardFormInput">\n' +
                '                            </label>\n' +
                '                        </form>\n' +
                '                    </div>\n' +
                '                </div>\n' +
                '                <h3 class="cardID">'+setId+'</h3>\n' +
                '           </div>')

        });
}

lorcanaCardData();