server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mastertcg
    username: mastertcg
    password: mastertcg
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true