ALTER TABLE inventory_vault_items
ADD COLUMN card_condition VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
ADD COLUMN available_for_trade BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN available_for_sale BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN notes TEXT;